# Generated by Django 3.0.3 on 2020-02-22 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_auto_20200222_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticket.Department'),
        ),
    ]
