# Generated by Django 3.0.3 on 2020-04-11 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_auto_20200411_1857'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'permissions': (('can_create_task', 'User Can Create a new task'), ('can_update_task', 'User Can update a task'))},
        ),
    ]
