# Generated by Django 3.0.3 on 2020-04-16 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_auto_20200411_1950'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
    ]
