# Generated by Django 3.0.1 on 2020-01-20 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_executor', models.BooleanField()),
                ('is_manager', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('text', models.TextField()),
                ('priority_client', models.CharField(choices=[('n', 'normal'), ('l', 'low'), ('h', 'high')], default='n', help_text='For chosing priority your task', max_length=1)),
                ('priority_executor', models.CharField(choices=[('n', 'normal'), ('l', 'low'), ('h', 'high')], default='n', max_length=1)),
                ('status', models.CharField(choices=[('2d', 'todo'), ('iw', 'inwork'), ('rv', 'review'), ('dn', 'done'), ('pp', 'postponed')], default='2d', max_length=10)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client', to='ticket.Client')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.Department')),
                ('executor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executor', to='ticket.Client')),
                ('tag', models.ManyToManyField(blank=True, to='ticket.Tag')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.Department'),
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
